version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  file_reader:
    build:
      context: ./file_reader
      dockerfile: file_reader.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
        - ../data:/code/data_files

  raw_data_receiver:
    build:
      context: ./raw_data_receiver
      dockerfile: raw_data_receiver.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  funniness_analyzer:
    build:
      context: ./funniness_analyzer
      dockerfile: funniness_analyzer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
