version: '3'
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    ports:
      - 15672:15672

  file_reader:
    build:
      context: ./file_reader
      dockerfile: file_reader.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - NUM_OF_DATA_RECEIVERS=4
      - PYTHONUNBUFFERED=1
    volumes:
        - ../data:/code/data_files

  raw_data_receiver:
    build:
      context: ./raw_data_receiver
      dockerfile: raw_data_receiver.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  funniness_analyzer:
    build:
      context: ./funniness_analyzer
      dockerfile: funniness_analyzer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  threshold_analyzer:
    build:
      context: ./threshold_analyzer
      dockerfile: threshold_analyzer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  rating_analyzer:
    build:
      context: ./rating_analyzer
      dockerfile: rating_analyzer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  same_text_identifier:
    build:
      context: ./same_text_identifier
      dockerfile: same_text_identifier.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  thresh_and_rating_analyzer:
    build:
      context: ./thresh_and_rating_analyzer
      dockerfile: thresh_and_rating_analyzer.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  bot_detector:
    build:
      context: ./bot_detector
      dockerfile: bot_detector.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  histogram:
    build:
      context: ./histogram
      dockerfile: histogram.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1

  sink:
    build:
      context: ./sink
      dockerfile: sink.dockerfile
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
